version: "3"

services:
  vector-embedding-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: vector-embedding-server:latest
    environment:
      TZ: Europe/Berlin
    ports:
      - "8080:8080"
