on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

name: linting and testing

jobs:
  test:
    name: Automatic linting and testing
    runs-on: ubuntu-latest

    env:
      JWT_SECRET_KEY: "my-super-secret-key"
      USERNAME: "BCH"
      HASHED_PASSWORD: "$2b$12$YP6UgESiJ6.3c0EwnxNEnu9Ts075Jz82AcqawG7fxvFiMSUgs6cWK"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.10.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - name: Setup Poetry 1.5.1
        run: pip install poetry==1.5.1

      - name: Check pyproject.toml
        run: poetry check

      - name: Install python dependencies with Poetry
        run: poetry install

      - name: Check files with isort
        run: poetry run isort . --check

      - name: Check files with Black
        run: poetry run black . --check

      - name: Lint files with flake8
        run: poetry run flake8

      - name: Check types with mypy
        run: poetry run mypy

      - name: Run tests
        run: poetry run pytest